[pytest]
# Opciones por que se aplicaran siempre al escribir pytest en la terminal.
addopts = -v --html=report.html --self-contained-html

markers =
    get: Pruebas GET
    post: Pruebas POST
    put: Pruebas PUT
    delete: Pruebas DELETE
    patch: Pruebas PATCH